### ISSUE TITLE
sorted dicts

### ISSUE THREAD

**Issue by bjarthur** [tshort/Eyeball.jl#27]
i find it useful to sort dicts when displaying them:  `using DataStructures; eye(SortedDict(mydict))`.  the problem is that only works at the top level, and my trees typically have nested dicts.  would be nice to have a menu option to sort a node that is a dict.  happy to help if you point me in the right direction.

**Comment by tshort** [comment]
The easiest approach is to define another key to sort and display an object. Here's a first cut (untested) at adapting [this](https://github.com/tshort/Eyeball.jl/blob/4ecf3150d43a00b456c7dec7e4591806d40e4cd6/src/Eyeball.jl#L165-L169):

```jl
        elseif i == Int('S')
            node = FoldingTrees.setcurrent!(menu, menu.cursoridx)
            println(term.out_stream, "\n\nOpening sort(`$(node.data.key)`) ...\n")
            choice = eye(sort(node.data.value))
            resetterm()
```
This should launch a new window just showing the sorted content.

**Comment by bjarthur** [comment]
awesome!  tried it and it works great.  i would suggest to add a check that the node is sortable, and to document it:

```
        elseif i == Int('S') 
            node = FoldingTrees.setcurrent!(menu, menu.cursoridx)
            length(methods(sort, (typeof(node.data.value),)))==0 && return false    ### here
            println(term.out_stream, "\n\nOpening sort(`$(node.data.key)`) ...\n")
            choice = eye(sort(node.data.value))
            resetterm()
```

shall i submit a PR?

**Comment by tshort** [comment]
Sure!
